### ISSUE TITLE
Where is auto_annotations/annotators/annotator_pool_v0/configs.yaml ?

### ISSUE THREAD

**Issue by HaSai666** [tatsu-lab/alpaca_farm#30]
<img width="1635" alt="截屏2023-05-30 12 46 28" src="https://github.com/tatsu-lab/alpaca_farm/assets/33769662/497d9a0d-ec69-460f-99d6-6073c0078c00">

I'm encountering a problem while initializing PairwiseAutoAnnotator. It requires the alpaca_farm/auto_annotations/annotators/annotator_pool_v0/configs.yaml configuration file, which seems to be missing from the expected path. I have updated to the latest GitHub repository, but I still can't find this configuration file even in the updated repository. Could you advise me on how to resolve this?

**Comment by lxuechen** [comment]
This will be fixed in a future release of the standalone evaluation package. For now, please install in dev mode to avoid this issue with `pip install -e . ` in the repo root.
