### ISSUE TITLE
Can you provide another graph of reward model over-optimization in Figure.5 of the paper?

### ISSUE THREAD

**Issue by twidddj** [tatsu-lab/alpaca_farm#33]
Can we detect the over-optimization in the use of the single consistent annotator (e.g., $p_{sim}^{GPT4}$) when it is compared to $p_{sim}^{eval}$ in the y-axis?

**Comment by lxuechen** [comment]
Hi, thanks for the question! We didn't perform this exact experiment in the paper. Since this isn't a question about the software, please email us to follow up and discuss. Thanks again!
