### ISSUE TITLE
`_name_or_path` is not stored in llama config.json any more

### ISSUE THREAD

**Issue by nrailgun** [tatsu-lab/alpaca_farm#34]
https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py#L237

but it is still used in `src/alpaca_farm/common.py:get_pretrained_model_name_with_model_name_or_path` to obtain model family.

At the sft stage, I used a local directory path as `--model-name-or-path`, and the local dir path is stored as `_name_or_path` in config.json. Then `get_pretrained_model_name_with_model_name_or_path` loaded llama config.json and failed to lookup `'_name_or_path'`.

**Comment by lxuechen** [comment]
Thanks for raising this issue. This has been resolved in a recent PR.

**Comment by nrailgun** [comment]
> Thanks for raising this issue. This has been resolved in a recent PR.

thank u .
