### ISSUE TITLE
cannot import name 'PairwiseAutoAnnotator' from partially initialized module 'alpaca_farm.auto_annotations' (most likely due to a circular import)

### ISSUE THREAD

**Issue by simplelifetime** [tatsu-lab/alpaca_farm#46]
Thanks for your excellent work! I want to reproduce the automatic evaluation and follow exactly the same procedure to configure my environment, but still get the error. Is there something wrong about the package dependency?

**Comment by lxuechen** [comment]
Thanks for raising the issue. It is fixed in a recent PR.
