### ISSUE TITLE
Generation Issue (probability tensor contains either `inf`, `nan` or element < 0) of Flash-LLaMA with Model Parallelism

### ISSUE THREAD

**Issue by Zhiyuan-Zeng** [tatsu-lab/alpaca_farm#48]
I am trying to use Flash-LLaMA with Huggingface model parallelism on 2 A100-80GB GPUs, and I built up my environment following the README in AlpacaFarm GitHub Repo (the version of package flash-attn is 1.0.7). I found that the generation (using model.generate() for sampling) seems to cause the issue "RuntimeError: probability tensor contains either `inf`, `nan` or element < 0". The LLaMA w/o Flash-Attention works well. Also, turning off model parallelism (i.e., with only 1 GPU) seems to not have such an issue.

Before running the code, we need to change this [line](https://github.com/tatsu-lab/alpaca_farm/blob/main/src/alpaca_farm/flash_models/flash_llama.py#L174), where we should add `.to(tensor.device)` after `position_ids`.

The code and input file are [here](https://drive.google.com/file/d/1jVPXknEJzW7_AfInPOgvPQf2PuMVKrSf/view?usp=sharing).

The code:
```python
import torch
from alpaca_farm import common
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--flash_attn", required = True, type = int)
args = parser.parse_args()

assert torch.cuda.device_count() == 2

args.flash_attn = bool(args.flash_attn)
print("Turn on Flash-Attention : {}".format(args.flash_attn))
model_name_or_path = "../../tatsu-lab/sft10k" # The path to sft10k
model = common.make_generative_lm(
            model_name_or_path = model_name_or_path,
            flash_attn = args.flash_attn,
            fp16 = False,
            bf16 = True,
            low_cpu_mem_usage = True,
            device_map = "auto",
            torch_dtype = torch.bfloat16,
        )

inputs = torch.load("inputs.bin")
input_ids = inputs["queries"].cuda()
attention_mask = inputs["query_attn_masks"].cuda()
responses = model.generate(
            inputs = input_ids,
            attention_mask = attention_mask,
            do_sample = True,
            max_new_tokens = 320,
            pad_token_id = 32000,
            top_p = 1.0,
            top_k = 0,
            temperature = 1.0,
            num_return_sequences = 1,
            # synced_gpus=True,
        )
print(responses)
```

**Comment by Zhiyuan-Zeng** [comment]
> Thanks for reporting! How was inputs.bin generated?

It is a batch of input when doing PPO. PPO feeds this batch of queries to the model to get the responses.

**Comment by Tiiiger** [comment]
Hi @Zhiyuan-Zeng ,

I don't think we ever use the huggingface "model parallelism" directly. So, Just chiming in for some thoughts. 

According to https://huggingface.co/docs/accelerate/usage_guides/big_modeling, 

> By passing device_map="auto", we tell 🤗 Accelerate to determine automatically where to put each layer of the model depending on the available resources:
> - first we use the maximum space available on the GPU(s)
> - if we still need space, we store the remaining weights on the CPU
> - if there is not enough RAM, we store the remaining weights on the hard drive as memory-mapped tensors

So in your case (using 80GB A100), your code should be loading the model onto the first GPU? Can you confirm if this is the case?

**Comment by Zhiyuan-Zeng** [comment]
Hi @Tiiiger,

- Yes I want to use model parallelism for my own use.
- I print the `model.hf_device_map`, and the result is `{'model.embed_tokens': 0, 'model.layers.0': 0, 'model.layers.1': 0, 'model.layers.2': 0, 'model.layers.3': 0, 'model.layers.4': 0, 'model.layers.5': 0, 'model.layers.6': 0, 'model.layers.7': 0, 'model.layers.8': 0, 'model.layers.9': 0, 'model.layers.10': 0, 'model.layers.11': 0, 'model.layers.12': 0, 'model.layers.13': 0, 'model.layers.14': 0, 'model.layers.15': 0, 'model.layers.16': 1, 'model.layers.17': 1, 'model.layers.18': 1, 'model.layers.19': 1, 'model.layers.20': 1, 'model.layers.21': 1, 'model.layers.22': 1, 'model.layers.23': 1, 'model.layers.24': 1, 'model.layers.25': 1, 'model.layers.26': 1, 'model.layers.27': 1, 'model.layers.28': 1, 'model.layers.29': 1, 'model.layers.30': 1, 'model.layers.31': 1, 'model.norm': 1, 'lm_head': 1}`. So I think the model is loaded onto the first two GPUs.

**Comment by Tiiiger** [comment]
Unfortunately we have no experience with this vanilla model parallelism and unsure why it is causing trouble. 

For all of this project, we used FSDP, which we find the most useful. I would suggest you look into how we used that and see if it can help.

**Comment by Zhiyuan-Zeng** [comment]
@Tiiiger Thanks for your help! Let me close this issue.
