### ISSUE TITLE
[tokenization] preprocessing inputs and labels

### ISSUE THREAD

**Issue by ArashAhmadian** [tatsu-lab/alpaca_farm#51]
Hello, 

Firstly thanks for open-sourcing all components of ``alpaca_farm``! 

I'm looking into ``data_preprocessor.py`` and am wondering where/if the `labels` are set to the `input_ids` shifted by 1. (something like ``input_ids = input_ids[...,1:]  labels = input_ids[...,:-1]``classic next token prediction) 

However, it seems like they're set to ``input_ids`` without any shifting? I'm not sure what I'm missing but any clarification would be great :) 

<img width="826" alt="Screen Shot 2023-06-25 at 5 54 51 PM" src="https://github.com/tatsu-lab/alpaca_farm/assets/70601261/52004b45-7f3f-47a7-a7e4-10276ad09432">

**Comment by ArashAhmadian** [comment]
NVM, for baseline ``sft``, since a default hugging-face trainer is used, shifting happens inside the default ``forward`` implementation :)) 
<img width="491" alt="Screen Shot 2023-06-25 at 6 10 24 PM" src="https://github.com/tatsu-lab/alpaca_farm/assets/70601261/1d3a8389-1227-491e-a6e8-33413809fc79">

**Comment by lxuechen** [comment]
Yeah, you’re right. Shifting is handled internally in the trainer.
