### ISSUE TITLE
[Discussion] Adding more diverse annotators representing subpopulations?

### ISSUE THREAD

**Issue by mensch72** [tatsu-lab/alpaca_farm#55]
I plan to study diversity-related aspects of RLHF, so I wonder how I could add more annotators that represent relevant subpopulations, so that the annotator pool is as representative as possible, but without making the annotators behave like stereotypes. 
I fear that simply adding something like "You live in the US and are a registered voter of the Democratic Party" or "you are a subsistence farmer in rural India" will not be the right approach...

**Comment by lxuechen** [comment]
Thanks for your interest! 

> I plan to study diversity-related aspects of RLHF, so I wonder how I could add more annotators that represent relevant subpopulations, so that the annotator pool is as representative as possible, but without making the annotators behave like stereotypes. 

I think the "without...stereotypes" part is a general research question requiring some experimentation (mostly prompting). Note this may be API-model dependent and task-dependent, and ultimately there's no formal guarantee. 

Regarding how one can run these prompting experiments with our codebase, you can add your custom prompts [here](https://github.com/tatsu-lab/alpaca_farm/tree/main/src/alpaca_farm/auto_annotations/annotators), and change the value to [this input argument](https://github.com/tatsu-lab/alpaca_farm/blob/19fb3918b009c4c6ffffcabe05cd871ffd743be0/src/alpaca_farm/auto_annotations/eval.py#L88) to point to the folder of prompts and configurations. 

Closing this issue now, but feel free to reopen if you have further questions.
