### ISSUE TITLE
Problem with Simulation case 

### ISSUE THREAD

**Issue by qiuruiyu** [tatsu-lab/alpaca_farm#61]
Hello, when using code in **Simulating pairwise preference**, I set os.environ with OPENAI_API_KEY. However, it raises error when I tried to create an instance of `PairwiseAutoAnnotator` with: 

NameError: name 'DUMMY_EXAMPLE' is not defined

**Comment by qiuruiyu** [comment]
您好，感谢您的来信。已确认收到您的邮件，我会尽快处理您的邮件，谢谢。Hello！This is an automatic reply confirming that your email was received. Your email will be handled as soon as possible. Thank you！                                                      仇睿瑜                                              Joseph QIUThis is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by YannDubs** [comment]
Thanks @qiuruiyu if you `pip install -U alpaca_farm` or pull from main it should work!
