### ISSUE TITLE
[Bug] Error importing is_deepspeed_zero3_enabled

### ISSUE THREAD

**Issue by SingL3** [tatsu-lab/alpaca_farm#65]
https://github.com/tatsu-lab/alpaca_farm/blob/7ae83ae8e839a86c2c819112a242e7f2442af490/src/alpaca_farm/common.py#L32
should be:
```
from transformers.trainer import WEIGHTS_NAME
from transformers.deepspeed import is_deepspeed_zero3_enabled
```

**Comment by lxuechen** [comment]
Thanks. This is caused by the transformers library upgrade. I have tightened the version to avoid this problem.
