### ISSUE TITLE
Use with Llama-2-70b-hf?

### ISSUE THREAD

**Issue by mensch72** [tatsu-lab/alpaca_farm#69]
We try to use alpaca_farm with the Llama-2-70b-hf model as downloaded from `https://huggingface.co/meta-llama/Llama-2-70b-hf` since the original llama-7b-hf seems to be taken down from HuggingFace (at least `https://huggingface.co/meta-llama/Llama-7b-hf` gives a 404).
When we put 
```python pretrained_models/recover_model_weights.py --llama-7b-hf-dir ../Llama-2-70b-hf/ --alpaca-farm-model-name all```
we get
```
Downloading sft10k
Traceback (most recent call last):
  File "/p/projects/ou/labs/gane/rlhf/git/alpaca_farm-collective/pretrained_models/recover_model_weights.py", line 112, in <module>
    model_tuned, tokenizer_tuned = load_weight_diff(hf_hub_name, is_reward_model, args.device, args.path_to_sft10k)
  File "/p/projects/ou/labs/gane/rlhf/git/alpaca_farm-collective/pretrained_models/recover_model_weights.py", line 48, in load_weight_diff
    model_tuned = transformers.AutoModelForCausalLM.from_pretrained(
  File "/p/projects/ou/labs/gane/rlhf/envs/alpaca-env/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 434, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/p/projects/ou/labs/gane/rlhf/envs/alpaca-env/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 873, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/p/projects/ou/labs/gane/rlhf/envs/alpaca-env/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 579, in __getitem__
    raise KeyError(key)
KeyError: 'llama'
```
even though the `config.json` in the specified folder contains the entry `"model_type": "llama"` :
```
{
  "_name_or_path": "meta-llama/Llama-2-70b-hf",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 8192,
  "initializer_range": 0.02,
  "intermediate_size": 28672,
  "max_position_embeddings": 4096,
  "model_type": "llama",
  "num_attention_heads": 64,
  "num_hidden_layers": 80,
  "num_key_value_heads": 8,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.32.0.dev0",
  "use_cache": true,
  "vocab_size": 32000
}
```
I wonder if this is due to the size mismatch (70b vs 7b) or the version mismatch (llama-2 vs llama) or some other issue. Any ideas?

**Comment by lxuechen** [comment]
Hi, thanks for reporting this. 

Size mismatch would definitely be one big issue. Since you're trying to run the recovery script, which is essentially running weights addition under the hood, we expect the base checkpoint to be exactly the original 7b checkpoint in hugging face format.

**Comment by mensch72** [comment]
OK, then I need to find a way to obtain Llama-1 rather than Llama-2. Any hints are welcome.

**Comment by lxuechen** [comment]
I think there are third-party weights on [spaces](https://huggingface.co/) if you search for llama there. Let me know how it goes!

**Comment by mensch72** [comment]
I tried the llama-7b-hf from https://huggingface.co/decapoda-research/llama-7b-hf which looks like it is a copy of the original. Still, I get the exact same error as in my first comment above. 
Can you point me to any version of llama that *should* work, so that I can rule out that it is a problem with the model?
