### ISSUE TITLE
Confusing detail preference mapping

### ISSUE THREAD

**Issue by dorothee-sigg** [tatsu-lab/alpaca_farm#71]
Just a little detail: 

In the example notebook auto_annotations.ipynb you write: 

`'preference':` the index of the preferred output, here `preference=2` so `output_1` is prefered.

Shouldn't preference 2 be mapped to output_2 ? Thanks.

**Comment by YannDubs** [comment]
thanks @dorothee-sigg it should be `preference=1` so `output_1`! Changed
