### ISSUE TITLE
lower cuda version? 

### ISSUE THREAD

**Issue by dorothee-sigg** [tatsu-lab/alpaca_farm#77]
I tried to execute the following snippet which turned out to require cuda>=11.0, however I only have access to a 10.2 version. Is there a way to specify another cuda version, e.g. in reward_modeling.sh ? Thanks

`bash examples/scripts/reward_modeling.sh \
  <your_output_dir_for_reward_model> \
  <your_wandb_run_name> \
  <your_output_dir_for_sft10k> \
  <preference_dataset_name>`

**Comment by lxuechen** [comment]
I haven't tested things for CUDA 10.2, sorry. You may want to upgrade your CUDA installation.
