### ISSUE TITLE
score with reward model

### ISSUE THREAD

**Issue by qlduNLP** [tatsu-lab/alpaca_farm#79]
Hi, thanks for sharing the great project!
I want to score the instruction pairs <instruction, input, output> with the pretrained reward model directly. How to use this system to achieve it?

**Comment by shunzh** [comment]
Hi, I did implement this, but our fork is not ready for release yet. I think the code you need is here. You can call `RLTrainer.evaluate()` but set the sequences to be the ones that you want to evaluate.
https://github.com/tatsu-lab/alpaca_farm/blob/64e489c67ea502ab5fa944bebde3078c9722f6ee/src/alpaca_farm/rl/rl_trainer.py#L236-L242

**Comment by lxuechen** [comment]
Yup, that's the place to look at.
