### ISSUE TITLE
BaseAnnotator.__init__() got an unexpected keyword argument 'other_keys_to_keep'

### ISSUE THREAD

**Issue by xukefaker** [tatsu-lab/alpaca_farm#85]
Traceback (most recent call last):
  File "/disk2/data/xk/RLPHF/gpt4_annotate/run.py", line 73, in <module>
    main(args)
  File "/disk2/data/xk/RLPHF/gpt4_annotate/run.py", line 52, in main
    annotator = PairwiseAutoAnnotator(annotators_config=args.annotators, saving_path=args.saving_path, openai_api_key = args.open_ai_key)
  File "/root/anaconda3/envs/rlphf/lib/python3.10/site-packages/alpaca_farm/auto_annotations/eval.py", line 170, in __init__
    super().__init__(
  File "/root/anaconda3/envs/rlphf/lib/python3.10/site-packages/alpaca_eval/annotators/pairwise_evaluator.py", line 51, in __init__
    super().__init__(*args, **kwargs, primary_keys=self.input_keys + self.output_keys)
  File "/root/anaconda3/envs/rlphf/lib/python3.10/site-packages/alpaca_eval/annotators/base.py", line 436, in __init__
    super().__init__(*args, **kwargs)
TypeError: BaseAnnotator.__init__() got an unexpected keyword argument 'other_keys_to_keep'

It seems that the argument 'other_keys_to_keep' is not accepted by the BaseAnnotator. I check the initialization of PairwiseAutoAnnotator:
class PairwiseAutoAnnotator(eval_annotators.PairwiseAnnotator):
    def __init__(
        self,
        annotators_config: Union[eval_utils.AnyPath, list[dict[str, Any]]] = "annotator_pool_v0",
        input_keys: Sequence[str] = ("instruction", "input"),
        p_label_flip: Optional[float] = None,
        base_dir: eval_utils.AnyPath = ANNOTATORS_CONFIG_DIR,
        other_keys_to_keep: Sequence[str] = tuple(),
        **kwargs,
    ):
        super().__init__(
            annotators_config=annotators_config,
            input_keys=input_keys,
            p_label_flip=p_label_flip,
            base_dir=base_dir,
            **other_keys_to_keep=other_keys_to_keep,**
            **kwargs,
        )

environment information:
alpaca-eval               0.5.1                    pypi_0    pypi                                                                                   
alpaca-farm               0.1.9                    pypi_0    pypi    

How can I solve this problem? Thanks!

**Comment by sweetice** [comment]
The same issue. Did you solve it?

**Comment by syleedandekar** [comment]
I'm also running into this issue. Does anyone know a fix for it?

**Comment by syleedandekar** [comment]
I just commented out those lines and it worked

**Comment by YannDubs** [comment]
Sorry for that, it will be fixed this weekend as we will have to switch to using AlpacaEval given that `davinci-003` is depreciated.
