### ISSUE TITLE
PairwiseAutoAnnotator always "Annotating 0 examples with gpt4_3"

### ISSUE THREAD

**Issue by CharlesQ9** [tatsu-lab/alpaca_farm#86]
INFO:root:Annotating 0 examples with gpt4_3
INFO:root:Saving all annotations to ./eval_results/answer1.json
I am trying to compare two answers that are of low quality. I am wondering why it is always annotating 0 examples and always returns that "preferences"=0. It seems that the annotator skips the evaluation process. Is it because the answers are too meaningless?

**Comment by YannDubs** [comment]
No that's because by default we cache the result, so if you try to annotate twice the exact same input/outputs it will not reannotate to avoid unnecessary annotations. For more information about caching of annotations refer to [AlpacaEval](https://github.com/tatsu-lab/alpaca_eval/tree/main)
